# This is base config

[base]
    debug_mode="debug"
    time_location="Asia/Shanghai"
    is_product = false
    live_time =1000

[jwt]
    key="asdfasdf1234zxvasdfasdfasdf"
    duration  = 2678400

[redis]
    addr = "127.0.0.1:6379"
    password = ""
    max_active = 100
    max_idle = 100
    down_grade = false

[http]
    addr =":9004"                       # 监听地址, default ":8700"
    read_timeout = 10                   # 读取超时时长
    write_timeout = 10                  # 写入超时时长
    max_header_bytes = 20               # 最大的header大小，二进制位长度
    allow_ip = [                        # 白名单ip列表
        "127.0.0.1",
        "192.168.1.1"
    ]

[log]
    level = "atom"
    format = "console"
    enable_color = false
    disable_caller = true
    development    = true
    disable_stacktrace = false
    output_paths = [
    "/opt/logs/local.log"
    ]

    error_output_paths = [
     "/opt/logs/error.log"
    ]


[swagger]
    title="gin_scaffold swagger API"
    desc="This is a sample server celler server."
    host="127.0.0.1:8880"
    base_path=""
