# this is mongodb config

[mongodb]
       host = "192.168.37.142:27017"
       username = ""
       password = ""
       database = "forest"
       max_pool_size = 100
       max_open_conn = 2
       max_conn_idle_time = 0
       log_level =4
